"""Netplay imitation roster. Generated by hal/scripts/build_netplay_roster.py; do not edit by hand.

The 50 connect codes with the most train frames in the professional manifests of the player
identity sidecar, excluding the professionals' alternate accounts. Each row is (code, label, train frames).
"""

from typing import Final

PLAYER_IDENTITY_SIDECAR_SHA256: Final[str] = "54ccf8a2497fe240313117297ca2ea31158e08db2cc53c67e7aa46853a8dac1c"
PLAYER_VOCABULARY_SHA256: Final[str] = "c67c97c995ad033ea7f5b2223efce5b061394566439f091ff6e7aaa6a9d1cfd6"

PROFESSIONAL_ROSTER: Final[tuple[tuple[str, str, int], ...]] = (
    ("IBDW#0", "iBDW", 362757044),
    ("MANG#0", "Mang0", 289683058),
    ("JAH#516", "JahRidin", 252110698),
    ("COOK#671", "CookBook", 203696472),
    ("AMSA#0", "aMSa", 195431598),
    ("ZAIN#0", "Zain", 189425254),
    ("DSNP#958", "DesertSnoopy", 175855246),
    ("FRNZ#141", "Frenzy", 171431551),
    ("GING#345", "Ginger", 161772342),
    ("AKLO#381", "Aklo", 148797363),
    ("WIZZ#310", "Gosu", 142362983),
    ("SIDD#539", "Siddward", 139125879),
    ("666#666", "Solobattle", 132249418),
    ("TRIF#0", "Trif", 93945978),
    ("DAN#877", "Daniel", 89441617),
    ("KOD#0", "KoDoRiN", 89328768),
    ("CHUG#596", "Krudo", 86231666),
    ("FREN#129", "Friend", 85447215),
    ("SUTT#456", "Uhhei", 85111754),
    ("KJH#23", "KJH", 83088240),
    ("ILT#987", "ILikeTurtles", 76688766),
    ("MON#0", "Monotheon", 62710911),
    ("ISDS#767", "Isdsar", 61660680),
    ("KOTU#737", "M2K", 55891471),
    ("YCZ#667", "YCZ", 55032366),
    ("TECHN#0", "TechnoSpider", 52469929),
    ("G2W#0", "Grab2Win", 52078646),
    ("KING#911", "Wishmaker", 44141141),
    ("MOKY#475", "mr. dokie", 41734972),
    ("JCHU#536", "JChu", 36861523),
    ("THA#837", "FknSilver", 35762929),
    ("FAPT#275", "Faptori", 35474668),
    ("NULL#478", "null", 34626438),
    ("ULLI#944", "ullimc", 32215031),
    ("MAGI#732", "woo magi", 30320532),
    ("SSJ#998", "Mr Plow", 29141030),
    ("XELA#158", "Franz", 27409817),
    ("PHAI#591", "phillip", 23825394),
    ("NICKI#1", "Nicki", 22594927),
    ("RIKZ#401", "Rikzz", 22253020),
    ("FFF#641", "YouSoBadAtGame", 22148362),
    ("COOL#673", "Skawa", 21128111),
    ("DUCK#403", "Duck", 19507748),
    ("SALT#747", "Doja Cat", 19234738),
    ("REDX#668", "RedX", 19017642),
    ("KIM#148", "BobbyBigBallz", 14491479),
    ("LEAF#930", "leaf", 14212302),
    ("TWO#555", "2Saint", 13794901),
    ("JARC#370", "Jarcino", 13050800),
    ("MOF#366", "MOF", 12171651),
)
